---
name: "Sccache Action"
description: "Setup sccache action"
author: "mozilla"
inputs:
  version:
    description: "The installed sccache version."
    required: true
runs:
  using: "node16"
  main: "dist/setup/index.js"
  post: "dist/show_stats/index.js"
  # windows can't run `--show-stats` while server is running.
  post-if: runner.os != 'windows'
branding:
  icon: "star"
  color: "orange"
